spring:
  application:
    name: pdumbbell
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pdumbbell
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: db/migration
    validate-migration-naming: true
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
